### ISSUE TITLE
marker is not draggable

### ISSUE THREAD

**Issue by connor11528** [jay3dec/ReactApp#1]
I cannot move the marker!

**Comment by jay3dec** [comment]
@jasonshark I would recommend [enabling device emulation](https://developer.chrome.com/devtools/docs/device-mode) in chrome developer tools to view the app as a mobile app. And the drag should work.

**Comment by connor11528** [comment]
Okay yeah you're right! Works when using chrome mobile dev view

![screen shot 2015-05-14 at 12 55 02 pm](https://cloud.githubusercontent.com/assets/3578908/7640545/b1c5be88-fa38-11e4-9e63-bf63c2671a8a.png)

I guess reapp is sensitive to touch events and kind of ignores when clicking. I will view my reapp apps like this when testing from now on
